name: Integration Test
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Update action.yml to build locally
        run: |
          sed -i 's/.*image\:.*/  image\: \"Dockerfile\"/' action.yml
          cat action.yml
      - name: Self test
        id: selftest
        uses: ./
        with:
          include: "test/"
          find: "world"

      - name: Check outputs
        run: |
          test "${{ steps.selftest.outputs.fileFoundCount }}" == "1"
